name: tark_gpt_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  intl: ^0.19.0
  equatable: ^2.0.5
  dio: ^4.0.6
  # flutter_secure_storage: ^6.0.0
  json_annotation: ^4.7.0
  build_runner: ^2.3.2
  screenshot: ^2.1.0
  flutter_svg: ^1.1.5
  syncfusion_flutter_datepicker: ^20.3.50
  flutter_multi_formatter: ^2.8.0
  flutter_keyboard_visibility: ^5.4.0
  font_awesome_flutter: ^10.2.1
  dots_indicator: ^2.1.0
  currency_text_input_formatter: ^2.1.7
  pull_to_refresh: ^2.0.0
  camera: ^0.10.5+5
  animated_text_kit: ^4.2.2
  uuid: ^3.0.7
  url_launcher: ^6.1.6
  dotted_border: ^2.0.0+2
  pin_code_fields: ^7.4.0
  flutter_dotenv: ^5.0.2
  credit_card_validator: ^2.1.0
  package_info_plus: ^4.0.1
  nfc_manager: ^3.2.0
  shimmer: ^2.0.0
  easy_localization: ^3.0.1
  permission_handler: ^11.0.1
  avatar_glow: ^2.0.2
  ndef: ^0.3.1
  uni_links: ^0.5.1
  translit: ^2.0.1
  collection: ^1.17.1
  share_plus: ^7.1.0
  aws_s3_upload: ^1.5.0
  path_provider: ^2.0.2
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: any
  flutter_launcher_icons: ^0.9.2
  lint: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
